export const OPTIONS_KEY = "arctictab:options";

export const OPTIONS_DEFAULTS = {
  excludePinned: true,
  reorganizeGroups: false,
  groupIdenticalTogether: true,
  identicalOwnGroup: true,
  hideApplyGroups: false,
  hideRearrange: false,
  hideGroupCount: false,
  hideTabCount: false,
  hideStatus: true,
  autoApplyGroups: false,
  autoApplyNaming: true,
  nameStyle: "mixed",
  headSim: 0.22,
  curatedSim: 0.27,
  keywordFrac: 0.34,
  groupingRules: [],
  usePinning: true,
  useBookmark: false,
  autoPinTabOnDrag: true,
  autoPinGroupOnDrag: true,
  showSearchBar: true,
  showCopyState: false,
  hideTabTitle: false,
  hideTabHost: true,
  hideControlGroupSize: false,
  debugLogging: false,
};
